spring:
  datasource:
    url: jdbc:h2:mem:user_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: alex
    password: 
  h2:
    console:
    enabled: true
    path: /console